# Generated by Django 3.1.7 on 2021-04-14 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='massage',
        ),
        migrations.AddField(
            model_name='note',
            name='important',
            field=models.BooleanField(blank=True, default=False, verbose_name='Важно'),
        ),
        migrations.AddField(
            model_name='note',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='note',
            name='visiability',
            field=models.BooleanField(blank=True, default=True, verbose_name='Публичность'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 15, 18, 48, 13, 775262), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='note',
            name='public',
            field=models.BooleanField(blank=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Активно'), (1, 'Отложено'), (2, 'Выполнено')], default=0, verbose_name='Статус'),
        ),
    ]
